### ISSUE TITLE
[ToDo]

### ISSUE THREAD

**Issue by bambokianr** [bambokianr/rubiks-cube-game#2]
- [x] Definition of colors on each face
- [x] Put rounded edges on each piece
- [x] Add mouse's event listener - `onDocumentMouseDown`, `onDocumentMouseUp` and `onDocumentMouseMove`
- [ ] Track whether the mouse is in is a rotating cube area -> `rotatingCube` variable
- [ ] Track whether the mouse is in is a rotating face area -> `rotatingFace` variable
- [x] Define correct cursor behavior for each case (influence of `isMouseBeingClicked`, `rotatingCube` and `rotatingFace` variables)
- [ ] Implement scene lighting
- [x] Implement cube movement
- [ ] Implement face movement
- [ ] Improve rounding of the edges of each piece
- [ ] Load texture (solve the problem with CORS policy images)
